version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_database_user
      MYSQL_PASSWORD: your_database_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  nuxt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nuxt
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: your_database_user
      DB_PASSWORD: your_database_password
      DB_NAME: your_database_name
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
